#!/usr/bin/env bash
readonly PATH_HOME="${HOME}/"
readonly PATH_INIT="${HOME}/.config/vim/"
readonly PATH_SRC="${HOME}/.vim/src/"
readonly PATH_SRC_UTILS="${HOME}/.vim/src/utils/"
readonly PATH_SRC_SETTING_PLUGINS="${HOME}/.vim/src/setting_plugins/"

if [ "$(which nvim | wc --bytes)" -eq 0 ]; then
	sudo apt-get update \
		; apt-get -y install neovim \
		; sudo apt-get -y install python-neovim \
		; sudo apt-get -y install python3-neovim 2> /dev/null 1> /dev/null &
fi
if [ "$(which nvim | wc --bytes)" -eq 0 ]; then
	sudo apt update \
	 	; apt -y install neovim \
		; sudo apt -y install python-neovim \
		; sudo apt -y install python3-neovim 2> /dev/null 1> /dev/null &
fi
if [ "$(which nvim | wc --bytes)" -eq 0 ]; then
	curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage 2> /dev/null 1> /dev/null &
	chmod u+x nvim.appimage 2> /dev/null 1> /dev/null &
	./nvim.appimage --appimage-extract 2> /dev/null 1> /dev/null &
	./squashfs-root/AppRun --version 2> /dev/null 1> /dev/null &
	mv squashfs-root / && ln -s /squashfs-root/AppRun /usr/bin/nvim 2> /dev/null 1> /dev/null &
fi


readonly PATH_FILES=('events.vim' 'features.vim' 'index.vim' 'load_plugins.vim' \
'scheme.vim' 'settings.vim' 'variables.vim' 'mappings.vim' \
'setting_plugins/ale.vim' 'setting_plugins/coc.vim' 'setting_plugins/emmet.vim' \
'setting_plugins/index.vim' 'setting_plugins/nerd_tree.vim' \
'utils/index.vim' 'utils/string.vim')

rm -rf $PATH_SRC
rm -f "${PATH_HOME}.vimrc"
rm -f "${PATH_INIT}init.vim"

mkdir -p $PATH_HOME
mkdir -p $PATH_INIT
mkdir -p $PATH_SRC
mkdir -p $PATH_SRC_UTILS
mkdir -p $PATH_SRC_SETTING_PLUGINS

wget --no-verbose --directory-prefix=$PATH_INIT 'https://raw.githubusercontent.com/JuanDAC/my_vim_config/main/init.vim' &> /dev/null &
wget --no-verbose --directory-prefix=$PATH_HOME 'https://raw.githubusercontent.com/JuanDAC/my_vim_config/main/.vimrc' &> /dev/null &

for i in ${!PATH_FILES[@]}; do
	wget --no-verbose -O "${PATH_SRC}${PATH_FILES[$i]}" \
		"https://raw.githubusercontent.com/JuanDAC/my_vim_config/main/src/${PATH_FILES[$i]}" &> /dev/null &
done

touch ~/.my_vimrc

if [ "$(which nvim | wc --bytes)" -eq 0 ]; then
	if [ ! -f "~/.vim/autoload/plug.vim" ]; then
		curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
			https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim &> /dev/null &
	fi
else
	if [ ! -f "${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim" ]; then
		sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
			https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim' &> /dev/null &
	fi
	
	if [ "$(cat ~/.bash_aliases | grep "vim='nvim'" | wc --bytes)" -ne 0 ]; then
		echo "alias vim='nvim';alias rm='rm -i'" >> ~/.bash_aliases
	elif [ ! -f ~/.bash_aliases ]; then
		echo "alias vim='nvim';alias rm='rm -i'" >> ~/.bash_aliases
	fi
fi

if [ "$(cat ~/.bashrc | grep "build_config_vim" | wc --bytes)" -ne 0 ]; then
	number="$(grep -n build_config_vim -- ~/.bashrc | cut --delimiter=':' --fields=1 | head -1)"
	if [ "$number" -ne 0 ]; then
		sed -i "${number}d" ~/.bashrc
		number=((number + 1))
		sed -i "${number}d" ~/.bashrc
	fi
fi	

if [ "$(cat ~/.bashrc | grep "build_config_vim" | wc --bytes)" -eq 0 ]; then
	echo "wget --no-verbose -O - https://raw.githubusercontent.com/JuanDAC/my_vim_config/main/build_config_vim | bash &> /dev/null &
	clear" >> ~/.bashrc
fi
