#!/usr/bin/env bash

readonly PATH_INIT='~/.config/vim/'
readonly PATH_SRC_UTILS='~/.vim/src/utils/'
readonly PATH_SRC_SETTING_PLUGINS='~/.vim/src/setting_plugins/'
readonly PATH_SRC='~/.vim/src/'

mkdir -p $PATH_INIT
mkdir -p $PATH_SRC
mkdir -p $PATH_SRC_UTILS
mkdir -p $PATH_SRC_SETTING_PLUGINS

wget --directory-prefix=$PATH_INIT
wget --directory-prefix=$PATH_SRC
wget --directory-prefix=$PATH_SRC_UTILS
wget --directory-prefix=$PATH_SRC_SETTING_PLUGINS
