#!/usr/bin/env bash

readonly PATH_HOME="${HOME}/"
readonly PATH_INIT="${HOME}/.config/vim/"
readonly PATH_SRC_UTILS="${HOME}/.vim/src/utils/"
readonly PATH_SRC_SETTING_PLUGINS="${HOME}/.vim/src/setting_plugins/"
readonly PATH_SRC="${HOME}/.vim/src/"
readonly PATH_FILES=('events.vim' 'features.vim' 'index.vim' 'load_plugins.vim' 'scheme.vim' 'settings.vim' 'variables.vim' \
'setting_plugins/ale.vim' 'setting_plugins/coc.vim' 'setting_plugins/emmet.vim' 'setting_plugins/index.vim' 'setting_plugins/nerd_tree.vim' \
'utils/index.vim' 'utils/string.vim')

rm -rf $PATH_SRC
rm -f "${PATH_HOME}.vimrc"
rm -f "${PATH_SRC}init.vim"

mkdir -p $PATH_HOME
mkdir -p $PATH_INIT
mkdir -p $PATH_SRC
mkdir -p $PATH_SRC_UTILS
mkdir -p $PATH_SRC_SETTING_PLUGINS

wget --directory-prefix=$PATH_INIT 'https://raw.githubusercontent.com/JuanDAC/my_vim_config/main/init.vim'
wget --directory-prefix=$PATH_HOME 'https://raw.githubusercontent.com/JuanDAC/my_vim_config/main/.vimrc'

for i in ${!PATH_FILES[@]}; do
	wget -O "${PATH_SRC}${PATH_FILES[$i]}" "https://raw.githubusercontent.com/JuanDAC/my_vim_config/main/src/${PATH_FILES[$i]}"
done
