set encoding=utf-8
scriptencoding utf-8
source ~/.vim/src/utils/index.vim
source ~/.vim/src/settings.vim
source ~/.vim/src/features.vim
source ~/.vim/src/load_plugins.vim
source ~/.vim/src/setting_plugins/index.vim
source ~/.vim/src/mappings.vim
source ~/.vim/src/scheme.vim
source ~/.vim/src/events.vim
